name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
          - StandaloneWindows64
          - StandaloneOSX
          - iOS
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
            
      - name: Decrypt & extract secrets
        run: ./decrypt_secret.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.ENCRYPTED_FILE_SECRET_PASSPHRASE }}

      - uses: actions/cache@v2
        with:
          path: Library
          key:
            Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ArcCreate

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  sendDiscordWebhook:
    name: Send Discord Webhook
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@v5.0.0"
        with:
          key: "${{secrets.DISCORD_WEBHOOK_KEY}}"
          payload: |
            {
              "username": "Github",
              "avatar_url": "https://i.imgur.com/XpJv9ci.png",
              "embeds": [
                {
                  "author": {
                    "name": "Github Action",
                    "icon_url": "https://i.imgur.com/XpJv9ci.png"
                  },
                  "title": "Build action completed: ${{ github.event.head_commit.message }}",
                  "description": "[Download build from here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})",
                }
              ]
            }
